### ISSUE TITLE
Consider adding `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by armandino** [chains-project/maven-lockfile#104]
I came across this project but haven't found the `CONTRIBUTING.md`. Please consider adding it for potential contributors to the project :)

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by MartinWitt** [comment]
https://github.com/chains-project/maven-lockfile/pull/107 Add first version for it.

**Comment by armandino** [comment]
@MartinWitt many thanks! :)
