### ISSUE TITLE
use Central checksums by default

### ISSUE THREAD

**Issue by monperrus** [chains-project/maven-lockfile#17]
generation time: two options for checksums
- compute them locally 
- collect them from Central

**Comment by MartinWitt** [comment]
More a note for me:
Add this as super hardend mode with a flag because this could require redownloading all of them.

**Comment by monperrus** [comment]
per today's meeting, we use the naming convention as an API

**Comment by monperrus** [comment]
per today's meeting, for sake of integrity, the checksums should be taken from Central at generation time.

**Comment by monperrus** [comment]
computing checksums locally could be done with an option/flag though

**Comment by monperrus** [comment]
Hi Martin,
Yes, we'll have those  options, but the naming is opposite.
The most secure, with most integrity, is to only trust remote checksums (from an external source).

* strict (default) Only use central checksum and **fail if there is none**
* local: download first and compute locally

Let's get this merged with two options, and later on we can work on a third mixed option.

**Comment by monperrus** [comment]
Per the discussion today we name the modes as follows:

* central (default) Only use central checksum and fail if there is none
* local: download first and compute locally
