### ISSUE TITLE
activate CI for the repo

### ISSUE THREAD

**Issue by monperrus** [chains-project/maven-lockfile#2]

**Comment by MartinWitt** [comment]
I tried to fix the issue but, to test this, we need tests and a released version.
Also the dependency is needed.
```xml
        <dependency>
            <groupId>org.apache.maven.plugin-testing</groupId>
            <artifactId>maven-plugin-testing-harness</artifactId>
            <version>3.3.0</version>
            <scope>test</scope>
        </dependency>
```
See this guide(https://maven.apache.org/plugin-testing/maven-plugin-testing-harness/getting-started/index.html). Also, for some reason this project uses junit 3.8. To my best knowledge IntelliJ simply fails to run junit 3 tests. Before starting with mojo testing, I would recommend adding renovate or update dependencies first.

**Comment by MartinWitt** [comment]
Ci works and is active
