### ISSUE TITLE
Default to a safe hash function when computing hashes locally

### ISSUE THREAD

**Issue by I-Al-Istannen** [chains-project/maven-lockfile#397]
SHA-1 is deprecated and attacks seem to be becoming more and more feasible. As maven uses SHA-1 hashes for remotes, we are also stuck with this decision when re-using them. However, if we compute hashes ourselves (as we probably should), we can default to a better hash function.

**Comment by MartinWitt** [comment]
SHA256 should be fine, or do you believe we should already adopt a more robust hash for local hashes?

**Comment by I-Al-Istannen** [comment]
SHA256 is probably fine and it is widely supported.
