### ISSUE TITLE
Make metadata environment section optional on the lockfile

### ISSUE THREAD

**Issue by massimeddu-sj** [chains-project/maven-lockfile#870]
Please introduce a parameter on the plugin to enable/disable the metadata.

We currently have different developers that are running on different environments (with different jvms). Currently the lockfile is updated every time another developer generate the lockfile because the environment is changed.

We would like to have a parameter `includeEnvironment` that permits to enable/disable the generation of the environment metadata (as we have a parameter to disable the generation of the mavenPlugins data).

The default behavior should be the current one (includeEnvironment=true), so no breaking changes are introduced.

**Comment by LogFlames** [comment]
Merged with #871

**Comment by massimeddu-sj** [comment]
Hi @LogFlames @monperrus do you have an expected date on when these changes will be released?

My team is currently relying on an internal fork with these patches, so I would like to understand if an when a release is planned, so I can migrate back from the fork to the main project.

Thank you.

**Comment by LogFlames** [comment]
I will look to create a release ASAP as I see no need to delay. This will however be the first release i publish, so it might take some time to initialize all accounts and for me to get the workflow running.

**Comment by monperrus** [comment]
thanks @LogFlames <https://github.com/LogFlames>

**Comment by LogFlames** [comment]
@massimeddu-sj Now we have released 5.2.0 :sparkles:
If there are any problems or oddities, don't hesitate to write letting me know!
