### ISSUE TITLE
Add a parameter to print a warning instead of failing the build in case the lockfile validation is not correct.

### ISSUE THREAD

**Issue by massimeddu-sj** [chains-project/maven-lockfile#873]
Sometimes, when a project with many internal dependencies is migrating to using the maven lockfiles, it could be difficult to achieve the migration in one step, leading to build failures if some dependency changes without updating the dependent components.

This proposal is to add an additional optional parameter `allowValidationFailure` (default: false) that, in case of lockfile validation failures generate a warning instead of make the build fails completely.

This also could enable projects adopting the plugin evaluating the impact of it, without disrupting the build process.

**Comment by LogFlames** [comment]
Introduced with #874
