### ISSUE TITLE
Github Action: Doesn't fail on invalid lockfile

### ISSUE THREAD

**Issue by LogFlames** [chains-project/maven-lockfile#880]
From the test #879 the github action don't seem to fail when "commit-lockfile" is set to false and the lockfile is invalid

**Comment by LogFlames** [comment]
This was a misunderstanding from my side. It tries to push the updated lockfile (only if it is changed), and if it failed to push it causes the action to fail.

The parameter "commit-lockfile" must therefore be set to true, for the process to fail in case of lockfile error

**Comment by LogFlames** [comment]
I think this is unexpected behaviour. 

If "commit-lockfile" is false, I expect it to verify the lockfile and succeed if it is correct and fail if it is incorrect, without trying to push the new lockfile to the branch.

**Comment by monperrus** [comment]
where is the reference documentation of flag "commit-lockfile"? If it does not exist, we have to write it first and settle on the reference behavior.
