### ISSUE TITLE
Github Action: Doesn't trigger on changed lockfile

### ISSUE THREAD

**Issue by LogFlames** [chains-project/maven-lockfile#881]
The github action currently only runs if `pom.xml` is updated, should this be run if the lockfile is updated aswell? Theoretically these should be synced, but now someone could change the lockfile and as long as the pom is unchanged, the github action would not fail/trigger regeneration.

**Comment by monperrus** [comment]
> The github action currently only runs if pom.xml is updated, should this be run if the lockfile is updated aswell?

yes, good catch!
